# Generated by Django 2.2.5 on 2019-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='speeddial',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
