# Generated by Django 2.2.5 on 2019-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.TextField(unique=True)),
                ('speeddial', models.TextField(null=True, unique=True)),
            ],
        ),
    ]
