# Generated by Django 2.2.5 on 2019-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num2name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='speeddial',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
