# Generated by Django 2.2.5 on 2019-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num2name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='number',
            field=models.TextField(unique=True),
        ),
    ]
